### ISSUE TITLE
Permission control 

### ISSUE THREAD

**Issue by fishren** [alvachien/mathexercise#11]
Hope to own permission to see Children's statistics.

**Comment by alvachien** [comment]
Let's put it open for now.

**Comment by alvachien** [comment]
UI app cannot control the authority directly.

Refer to #https://github.com/alvachien/acquizapi/issues/2

**Comment by alvachien** [comment]
Now enabled with https://github.com/alvachien/mathexercise/commit/12270a8cd11e356ce0387f04f9b12dfa21f8343a
