### ISSUE TITLE
Small award

### ISSUE THREAD

**Issue by fishren** [alvachien/mathexercise#13]
Can add some little awards and show to users when they achieved that.
And can also allow to unlock some advanced functions.

**Comment by alvachien** [comment]
@fishren Please provides detail from end user's point of view.

**Comment by alvachien** [comment]
refer to #44

**Comment by alvachien** [comment]
Award system now activated in commit https://github.com/alvachien/mathexercise/commit/bb91229ef793f16833a9420ccaa8616105cea2d6
